#!/usr/bin/env bash

# add more images here
declare -a docker_images=(
    "redis:6"
    "redis:5"
    "openjdk:11"
    "openjdk:18"
)

for image in "${docker_images[@]}"
do
    docker manifest inspect ghcr.io/mrc-ide/docker-official-images/"$image" > /dev/null 2>&1
    exit_code=$?

    if [ $exit_code -eq 0 ]; then
        echo "Not porting over $image because it already exists in the GHCR"
    else
        docker pull "$image"
        docker image tag "$image" ghcr.io/mrc-ide/docker-official-images/"$image"
        docker image push ghcr.io/mrc-ide/docker-official-images/"$image"
    fi
done
